from .left_heel_slides import do_left_heel_slides, TOTAL_STEPS as LHS_TOTAL
from .seated_right_knee_extension import do_seated_right_knee_extension, TOTAL_STEPS as SRKE_TOTAL
from .side_lying_left_leg_lift import do_side_lying_left_leg_lift, TOTAL_STEPS as SLLLL_TOTAL
